name: Slack Notification on Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: slack-send
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: sdk-releases
        slack-message: |
          New release: [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }})
          Repository: ${{ github.repository }}
          Author: ${{ github.event.release.author.login }}
          Release Notes: ${{ github.event.release.body }}
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  
